### ISSUE TITLE
The Anti-Tracking: Cryptomining Retention experiment is not working on Firefox versions older than 68

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/cryptomining-retention-study#2]
[Affected Versions]:
- Cryptomining Protections Retention Study v1.0
- Firefox 67
- Firefox 66

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the Firefox 67.0b15 unbranded version installed.
- Have the "xpinstall.signatures.dev-root" boolean pref set to "true".
- Have the Cryptomining Protections Retention Study add-on installed.
- Be enrolled in the "CM" branch.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "https://senglehardt.com/test/trackingprotection/test_pages/cryptomining.html" test page.
3. Observe if the Cryptominers are blocked.

[Expected results]:
- The Cryptominers are detected and blocked.

[Actual results]:
- The Cryptominers are not detected and not blocked.

[Notes]:
- The issue is not reproducible on the latest Nightly 68.0a1 builds. The Cryptominers are detected and blocked.
- Also, the "Cryptominers" is not displayed as blocked in the "about:preferences#privacy" page at "Standard" section. However, if you choose the "Custom" option, the "Cryptominers" option is checked.
- The prefs seems to be correctly set after installing the add-on.
- Attached a screen recording with the issue:
![crypto](https://user-images.githubusercontent.com/19226534/57145578-2d2a1780-6dcc-11e9-82c8-f48ad9a82559.gif)

**Comment by ericawright** [comment]
Hi Cosmin, 
We have 2 issues here. 
1. The UI is not explaining to the user that they have cryptominers blocked, this is because that UI change is not active until version 68. We can accept this.
2. Cryptominers appear to not be blocked, this is a url-classifier issue. Go to about:url-classifier, scroll down to the "provider" section and click "trigger update" on the lists. Cryptominers will not be blocked until ~1 hour after the experiment becomes active when the lists will update automatically. We are aware of this and can disregard the first hour of the experiment if needed.

I'm closing this as wontfix.
